= sailer_cli: Sailer-Remoteportal von der Kommandozeile
:toc:

Mit sailer_cli kann man Werte aus dem https://www.sailergmbh.de/de/produkte/systemregler/remote-portal.html[Remoteportal von SAILER] auslesen. 

Diese Werte kann man dann via https://mqtt.org/[MQTT] z.B. an https://www.home-assistant.io/[HomeAssistant] weitergeben.
Außerdem konnte man bzw. kann man noch Werte über HTTP direkt an den 
HomeAssistant-Server weitergeben.

Sailer_cli nutze ich für private, nicht kritische Use-Cases. Es funktioniert bei mir. 
Ob es bei anderen funktioniert, interessiert mich zwar - bitte bei Gelegenheit mitteilen!
Aber ich weiß es nicht und kann nur davor **warnen**, es einzusetzen, ohne vorher in den Code
geschaut zu haben.

== Vorbereitung 

```bash
  npm install
  npm install puppeteer
```

Setze 
  
  SAILER_PASSWORD=geheim
  SAILER_USER=sailerBenutzer
  HOME_ASSISTANT_TOKEN=geheimes_Long_Living_Token_aus_Home_Assistant_Einstellungen
  HOME_ASSISTANT_URL=https://SERVER:8124
  MQTT_SERVER_HOST=localhost
  MQTT_HA_DISCOVERY_PREFIX=myhome/homeassistant/mqtt_discovery

Erlaube das Ausführen der mit Puppeteer mitgelieferten Version von Chrome. Bitte aufwändigen
unter 
  https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md

beschriebenen Weg nutzen. Z.B mit einem AppArmor-Profil für den von Puppeteer unter $HOME/.cache/puppeteer/... 
installierten chrome:
  ```bash
    ./helpers/chromeSandbox.sh
  ```
  



Die folgende Alternative reißt ein großes Loch in die Sicherheit des 
Rechners und ist NICHT empfehlen:

```bash
  echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
```



== Compilieren


```bash
  npm run build
```

Nach dem ersten build sollte man ./dist/index.js ausführbar machen:
  
```bash
  chmod u+x ./dist/index.js
```

Ansonsten bekommt man die Fehlermeldung:
  
  sh: 1: sailer: Permission denied


== Benutzung

```bash
  npx sailer --version
  npx sailer --help
  npx sailer list-keys --help
  npx sailer list-keys
  npx sailer list-keys --filter "F3: Speicher"
  npx sailer list-keys --filter "^(F1: Kollektor|F3: Speicher)"
  npx sailer update-mqtt-state --filter "^(F1: Kollektor|F3: Speicher)" 
```

Die '''--filter'''-Option erlaubt reguläre Ausdrücke (RegEx).

== Entwicklung

=== Automatische Tests

Die automatischen Tests müssen noch deutlich erweitert werden.

```bash
  npm run test:watch
```
== Siehe auch

* https://www.sailergmbh.de/de/produkte/systemregler/remote-portal.html[Remote-Portal von Sailer Ehingen]
* https://www.home-assistant.io/[HomeAssistant]
* https://www.home-assistant.io/integrations/mqtt/[HomeAssistant MQTT integration]
* https://mosquitto.org/[Mosquitto], ein MQTT Broker
